### ISSUE TITLE
Background flickers when opening pop ups

### ISSUE THREAD

**Issue by Murderlon** [bettervim/yugen.nvim#2]
Hi, really like the color scheme! 

There is just one annoying thing which I don't have with other color schemes, which is how pop ups look. The background flickers and telescope doesn't look optimal either.

https://github.com/user-attachments/assets/c6cbc387-3aec-4727-ad66-228a13059ba5

**Comment by vmarcosp** [comment]
Hey @Murderlon, thanks a lot for reporting this!
That’s really odd. I’m using Telescope as well, and it seems to be working as expected on my config:

https://github.com/user-attachments/assets/3fb6231c-3f71-4a4d-afd9-a96975f2a394

Am I missing something? Did you just open Telescope and then close it? Also, which terminal emulator are you using?

**Comment by Murderlon** [comment]
I'm using LazyVim inside Kitty. Could it be that the background is set to transparent by default and it picks up your terminal color scheme instead? I see you use your custom Yugen Kitty theme, perhaps it's reproducible on your side if you use any other theme?

**Comment by Murderlon** [comment]
If I use your `yugen.conf` the colors are the same. So I can confirm what needs to happens is that all things that are transparent or are depending on terminal colors should be hardcoded to colors.

**Comment by neg4n** [comment]
Hey guys! I wanted to confirm that the issue also occurs when using fzf-lua instead of Telescope. As @Murderlon mentioned, the error is related to opening the popups and may not limited to Telescope. My terminal emulator is WezTerm.

**Comment by vmarcosp** [comment]
I've just released a fix that should resolve this issue. Could you please update your configuration and let me know if it works?
Here is my test using a different theme for the terminal (I'm using Kitty):

https://github.com/user-attachments/assets/666b5d83-fd90-4277-909c-76551f145dc5

**Comment by Murderlon** [comment]
That worked, thanks!
